settings:
  title: 'Status Page'
  url: 'https://re.o6.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 10 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:

  - id: docuteG # unique identifier
    name: docute GET
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://gre4a.1i.workers.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
       
  - id: docuteP # unique identifier
    name: docute POST
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://gre4a.1i.workers.dev/' # URL to fetch
    method: POST # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: re # unique identifier
    name: re
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://re.1i.workers.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: pbl-6a
    name: pbl-6a
    description: 'Built for anything connected to the Internet.'
    url: 'https://pbl-6a.web.app/'
    method: GET
    expectStatus: 200

  - id: gr0bot
    name: gr0bot
    url: 'https://gr0bot.web.app/'
    method: GET
    expectStatus: 200
