name = "r3"
workers_dev = true
account_id = "691a3156e374317f2c626559557a6f12"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
# [env.production]
# kv-namespaces = [{binding="KV_STATUS_PAGE", id="9627602ab75344eebd5f0b5e08b269b8", preview_id=""}]
#zone_id="xxx"
#route="xxx"
