name = "r3"
workers_dev = true
account_id = "691a3156e374317f2c626559557a6f12"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
kv-namespaces = [{binding="KV_STATUS_PAGE", id="4aecd1f4ceb34075bcafd02b03fcbe3c", preview_id=""}]

[vars]
B=''
TOKEN="929777422:AAEim6p-WwZwv_w7pBx5_P50o3lKEWTj75s"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
# [env.production]
 
#zone_id="xxx"
#route="xxx"
